steps:
- template: azure-pipelines.core.init-dotnet-tools.yml

- script: |
    dotnet cake build.cake --target=publish --artifacts-directory=$(Build.ArtifactStagingDirectory)
  displayName: Build - Publish

- task: PublishPipelineArtifact@0
  displayName: Publish - Artifacts
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)
    artifactName: ci-build

- script: |
    dotnet cake build.cake --target=clean --artifacts-directory=$(Build.ArtifactStagingDirectory)
  displayName: Clean - Build
