version: "3"

services:
  chef-client:
    build:
      context: ./build/docker/
      dockerfile: ./chef-client.Dockerfile

    volumes:
      - ${REPO_DIR}:C:/opt/docker/work/

  chocolatey:
    build:
      context: ./build/docker/
      dockerfile: ./chocolatey.Dockerfile

    volumes:
      - ${REPO_DIR}:C:/opt/docker/work/

    environment:
      CHOCOLATEY_SERVER:
      CHOCOLATEY_API_KEY:
