version: '3.5'

services:
  gitversion:
    image: gittools/gitversion-dotnetcore:windows-4.0.1
    isolation: hyperv
    volumes:
      - .:C:/data
    command:
      - C:/data
      - /showvariable
      - SemVer
