services:
  chocolatey:
    build:
      context: ./build/chocolatey/
      dockerfile: ./Dockerfile

    volumes:
      - ${REPO_DIR}:C:/opt/docker/work/

    environment:
      CHOCOLATEY_SERVER:
      CHOCOLATEY_API_KEY:
