name: CD Acceptance

on:
  workflow_run:
    workflows: ["CD Commit"]
    types: ["completed"]

jobs:
  build:
    name: CD Commit Build
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Init .NET
        run: dotnet tool restore

      - name: Download Chocolatey Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-chocolatey
          path: artifacts/chocolatey/

      - name: Publish Cake
        run: dotnet cake deploy.cake --target publish

      - name: Clean Cake
        run: dotnet cake build.cake --target clean
